version: '3.5'
services:
  nginx:
    container_name: nginx-ws-3
    volumes:
      - ./../:/var/www/site
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    image: nginx
    ports:
      - "8081:80"
    links:
      - fpm
    networks:
      - net
  fpm:
    container_name: fpm-ws-3
    build:
      context: ./fpm
      args:
        - UID
        - USER_NAME
    user: ${USER_NAME}
    working_dir: /var/www/site
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./../:/var/www/site
      - ./fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - net
  mysql:
    container_name: mysql-ws-3
    image: mariadb:10.4.12-bionic
    command: --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - 3307:3306
    networks:
      - net
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

networks:
  net:
    name: network-ws-3
    ipam:
      driver: default